#spring.datasource.url=jdbc:sqlserver://10.224.11.4.nip.io:1433;databaseName=Price1C;encrypt=true;trustServerCertificate=true;loginTimeout=30;
#spring.datasource.username=LocalFuchs
#spring.datasource.password=FuchsUA10!zxc
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#
#spring.datasource.hikari.maximumPoolSize=5
## ?????? ?? ??????????? ?? 45 ?????? (?????????? ???????? ?????? Azure -> OnPrem)
#spring.datasource.hikari.connection-timeout=45000
#
## ??????? ?'??????? "??????????" (????? 30 ??? ?????????, ??? ????? ?? ???????? ?????)
#spring.datasource.hikari.keepalive-time=30000
#
## ???????????? ??? ????? ?'??????? (30 ??????)
#spring.datasource.hikari.max-lifetime=1800000
#
## ????????? ?????????? ?'???????
#spring.datasource.hikari.validation-timeout=5000
#
##liqibase
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
