spring.datasource.url=jdbc:sqlserver://roting-service-prod:1433;databaseName=Price1C;encrypt=true;trustServerCertificate=true;loginTimeout=30;tcpKeepAlive=tru
spring.datasource.username=LocalFuchs
spring.datasource.password=FuchsUA10!zxc
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.hikari.maximumPoolSize=70
# ?????? ?? ??????????? ?? 45 ?????? (?????????? ???????? ?????? Azure -> OnPrem)
spring.datasource.hikari.connection-timeout=45000

# ??????? ?'??????? "??????????" (????? 30 ??? ?????????, ??? ????? ?? ???????? ?????)
spring.datasource.hikari.keepalive-time=90000

# ???????????? ??? ????? ?'??????? (30 ??????)
spring.datasource.hikari.max-lifetime=600000

# ????????? ?????????? ?'???????
spring.datasource.hikari.validation-timeout=5000

spring.datasource.hikari.minimum-idle=5

#liqibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
